// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AutoRemove(): $CancellablePromise<void> {
    return $Call.ByID(1549057170);
}

export function AutoRemovePreview(): $CancellablePromise<$models.CleanupResult | null> {
    return $Call.ByID(144280942).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Capabilities(): $CancellablePromise<$models.BrewCapabilities> {
    return $Call.ByID(2357783967).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(4077339923);
}

export function CleanupPreview(): $CancellablePromise<$models.CleanupResult | null> {
    return $Call.ByID(546646565).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Deps(name: string, tree: boolean): $CancellablePromise<string[]> {
    return $Call.ByID(1337062495, name, tree).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Doctor(): $CancellablePromise<$models.CommandResult | null> {
    return $Call.ByID(3558444530).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Info(name: string): $CancellablePromise<$models.FormulaInfo | null> {
    return $Call.ByID(3253190885, name).then(($result: any) => {
        return $$createType7($result);
    });
}

export function Install(name: string): $CancellablePromise<void> {
    return $Call.ByID(1909335040, name);
}

export function InstallPackage(name: string, packageType: string): $CancellablePromise<void> {
    return $Call.ByID(394624528, name, packageType);
}

export function ListInstalled(): $CancellablePromise<$models.InstalledListResult | null> {
    return $Call.ByID(3134767653).then(($result: any) => {
        return $$createType9($result);
    });
}

export function Outdated(): $CancellablePromise<$models.OutdatedListResult | null> {
    return $Call.ByID(3466609581).then(($result: any) => {
        return $$createType11($result);
    });
}

export function PackageInfo(name: string, packageType: string): $CancellablePromise<$models.PackageInfoResult | null> {
    return $Call.ByID(3588674495, name, packageType).then(($result: any) => {
        return $$createType13($result);
    });
}

export function Pin(name: string): $CancellablePromise<void> {
    return $Call.ByID(3061031924, name);
}

export function Reinstall(name: string, isCask: boolean): $CancellablePromise<void> {
    return $Call.ByID(142764307, name, isCask);
}

export function Search(query: string): $CancellablePromise<$models.SearchResult | null> {
    return $Call.ByID(1352804233, query).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(861965750, app);
}

export function Uninstall(name: string): $CancellablePromise<void> {
    return $Call.ByID(2342374137, name);
}

export function UninstallCask(name: string, zap: boolean): $CancellablePromise<void> {
    return $Call.ByID(1347681203, name, zap);
}

export function Unpin(name: string): $CancellablePromise<void> {
    return $Call.ByID(1784520513, name);
}

export function Update(): $CancellablePromise<void> {
    return $Call.ByID(4127468116);
}

export function Upgrade(name: string): $CancellablePromise<void> {
    return $Call.ByID(1583663319, name);
}

export function UpgradeAll(): $CancellablePromise<void> {
    return $Call.ByID(251164498);
}

export function Uses(name: string, installedOnly: boolean, recursive: boolean): $CancellablePromise<string[]> {
    return $Call.ByID(796080229, name, installedOnly, recursive).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CleanupResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BrewCapabilities.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.CommandResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.FormulaInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.InstalledListResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.OutdatedListResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.PackageInfoResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.SearchResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
