// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Check(filePath: string): $CancellablePromise<$models.BundleCheckResult | null> {
    return $Call.ByID(2714928423, filePath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Cleanup(filePath: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(487958931, filePath, force);
}

export function CleanupPreview(filePath: string): $CancellablePromise<$models.CommandResult | null> {
    return $Call.ByID(3880760229, filePath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Dump(filePath: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1470822119, filePath, force);
}

export function List(filePath: string): $CancellablePromise<string[]> {
    return $Call.ByID(2745044449, filePath).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ReadBrewfile(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(589227971, filePath);
}

export function Restore(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(1592418481, filePath);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(986277686, app);
}

// Private type creation functions
const $$createType0 = $models.BundleCheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CommandResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
