// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(423829810);
}

export function EffectiveBrewPath(): $CancellablePromise<string> {
    return $Call.ByID(2950353535);
}

export function Export(): $CancellablePromise<string> {
    return $Call.ByID(3973180209);
}

export function Get(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(389682165).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Import(content: string): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(3366032642, content).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Reset(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(370363850).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Save(input: $models.AppConfig): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(1279210262, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetMenuBarApplier(applier: any): $CancellablePromise<void> {
    return $Call.ByID(358247410, applier);
}

export function ValidateBrewPath(path: string): $CancellablePromise<$models.BrewPathValidation> {
    return $Call.ByID(2235763718, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ValidateStartupConfig(): $CancellablePromise<string> {
    return $Call.ByID(1805686484);
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
const $$createType1 = $models.BrewPathValidation.createFrom;
