// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AppConfig {
    "language": string;
    "theme": string;
    "brew_path": string;
    "brewfile_path": string;
    "auto_update_interval": string;
    "log_max_lines": number;
    "check_updates_on_launch": boolean;
    "launch_at_login": boolean;
    "show_in_menu_bar": boolean;
    "restore_last_page": boolean;
    "last_page_path": string;
    "backup_before_update": boolean;
    "cleanup_after_update": boolean;
    "notify_updates": boolean;
    "notify_operations": boolean;
    "notify_services": boolean;
    "notify_errors": boolean;
    "show_toasts": boolean;
    "toast_position": string;
    "keep_notification_history": boolean;
    "toast_duration_ms": number;
    "max_concurrency": number;
    "debug_log": boolean;
    "accent_hue": number;
    "ui_font_size": number;
    "row_density": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("brew_path" in $$source)) {
            this["brew_path"] = "";
        }
        if (!("brewfile_path" in $$source)) {
            this["brewfile_path"] = "";
        }
        if (!("auto_update_interval" in $$source)) {
            this["auto_update_interval"] = "";
        }
        if (!("log_max_lines" in $$source)) {
            this["log_max_lines"] = 0;
        }
        if (!("check_updates_on_launch" in $$source)) {
            this["check_updates_on_launch"] = false;
        }
        if (!("launch_at_login" in $$source)) {
            this["launch_at_login"] = false;
        }
        if (!("show_in_menu_bar" in $$source)) {
            this["show_in_menu_bar"] = false;
        }
        if (!("restore_last_page" in $$source)) {
            this["restore_last_page"] = false;
        }
        if (!("last_page_path" in $$source)) {
            this["last_page_path"] = "";
        }
        if (!("backup_before_update" in $$source)) {
            this["backup_before_update"] = false;
        }
        if (!("cleanup_after_update" in $$source)) {
            this["cleanup_after_update"] = false;
        }
        if (!("notify_updates" in $$source)) {
            this["notify_updates"] = false;
        }
        if (!("notify_operations" in $$source)) {
            this["notify_operations"] = false;
        }
        if (!("notify_services" in $$source)) {
            this["notify_services"] = false;
        }
        if (!("notify_errors" in $$source)) {
            this["notify_errors"] = false;
        }
        if (!("show_toasts" in $$source)) {
            this["show_toasts"] = false;
        }
        if (!("toast_position" in $$source)) {
            this["toast_position"] = "";
        }
        if (!("keep_notification_history" in $$source)) {
            this["keep_notification_history"] = false;
        }
        if (!("toast_duration_ms" in $$source)) {
            this["toast_duration_ms"] = 0;
        }
        if (!("max_concurrency" in $$source)) {
            this["max_concurrency"] = 0;
        }
        if (!("debug_log" in $$source)) {
            this["debug_log"] = false;
        }
        if (!("accent_hue" in $$source)) {
            this["accent_hue"] = 0;
        }
        if (!("ui_font_size" in $$source)) {
            this["ui_font_size"] = 0;
        }
        if (!("row_density" in $$source)) {
            this["row_density"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class BrewCapabilities {
    "brew_version": string;
    "supports_list_json_v2": boolean;
    "supports_tap_json": boolean;
    "supports_outdated_json_v2": boolean;
    "supports_info_installed_json_v2": boolean;
    "detected_at": time$0.Time;

    /** Creates a new BrewCapabilities instance. */
    constructor($$source: Partial<BrewCapabilities> = {}) {
        if (!("brew_version" in $$source)) {
            this["brew_version"] = "";
        }
        if (!("supports_list_json_v2" in $$source)) {
            this["supports_list_json_v2"] = false;
        }
        if (!("supports_tap_json" in $$source)) {
            this["supports_tap_json"] = false;
        }
        if (!("supports_outdated_json_v2" in $$source)) {
            this["supports_outdated_json_v2"] = false;
        }
        if (!("supports_info_installed_json_v2" in $$source)) {
            this["supports_info_installed_json_v2"] = false;
        }
        if (!("detected_at" in $$source)) {
            this["detected_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrewCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): BrewCapabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrewCapabilities($$parsedSource as Partial<BrewCapabilities>);
    }
}

export class BrewPathValidation {
    "path": string;
    "valid": boolean;
    "version": string;
    "error": string;

    /** Creates a new BrewPathValidation instance. */
    constructor($$source: Partial<BrewPathValidation> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrewPathValidation instance from a string or object.
     */
    static createFrom($$source: any = {}): BrewPathValidation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrewPathValidation($$parsedSource as Partial<BrewPathValidation>);
    }
}

export class BrewServicesResult {
    "name": string;
    "status": string;
    "user": string;
    "file": string;
    "exit_code": number;

    /** Creates a new BrewServicesResult instance. */
    constructor($$source: Partial<BrewServicesResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("exit_code" in $$source)) {
            this["exit_code"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrewServicesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BrewServicesResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrewServicesResult($$parsedSource as Partial<BrewServicesResult>);
    }
}

export class BundleCheckResult {
    "satisfied": boolean;
    "missing": string[];
    "output": string;

    /** Creates a new BundleCheckResult instance. */
    constructor($$source: Partial<BundleCheckResult> = {}) {
        if (!("satisfied" in $$source)) {
            this["satisfied"] = false;
        }
        if (!("missing" in $$source)) {
            this["missing"] = [];
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BundleCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BundleCheckResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("missing" in $$parsedSource) {
            $$parsedSource["missing"] = $$createField1_0($$parsedSource["missing"]);
        }
        return new BundleCheckResult($$parsedSource as Partial<BundleCheckResult>);
    }
}

export class CaskInfo {
    "name": string;
    "full_name": string;
    "tap": string;
    "desc": string;
    "homepage": string;
    "version": string;
    "installed": string;
    "auto_updates": boolean;
    "token": string;

    /** Creates a new CaskInfo instance. */
    constructor($$source: Partial<CaskInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("full_name" in $$source)) {
            this["full_name"] = "";
        }
        if (!("tap" in $$source)) {
            this["tap"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = "";
        }
        if (!("auto_updates" in $$source)) {
            this["auto_updates"] = false;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaskInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CaskInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaskInfo($$parsedSource as Partial<CaskInfo>);
    }
}

export class CleanupResult {
    "cleaned_count": number;
    "size_reclaimed": string;
    "output": string;

    /** Creates a new CleanupResult instance. */
    constructor($$source: Partial<CleanupResult> = {}) {
        if (!("cleaned_count" in $$source)) {
            this["cleaned_count"] = 0;
        }
        if (!("size_reclaimed" in $$source)) {
            this["size_reclaimed"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanupResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CleanupResult($$parsedSource as Partial<CleanupResult>);
    }
}

export class CommandResult {
    "success": boolean;
    "output": string;
    "duration": string;
    "error"?: string;

    /** Creates a new CommandResult instance. */
    constructor($$source: Partial<CommandResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult($$parsedSource as Partial<CommandResult>);
    }
}

export class FormulaInfo {
    "name": string;
    "full_name": string;
    "tap": string;
    "desc": string;
    "homepage": string;
    "license": string;
    "stable_version": string;
    "head_version": string;
    "linked_keg": string;
    "pinned": boolean;
    "installed": KegInfo[];
    "dependencies": string[];

    /** Creates a new FormulaInfo instance. */
    constructor($$source: Partial<FormulaInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("full_name" in $$source)) {
            this["full_name"] = "";
        }
        if (!("tap" in $$source)) {
            this["tap"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("license" in $$source)) {
            this["license"] = "";
        }
        if (!("stable_version" in $$source)) {
            this["stable_version"] = "";
        }
        if (!("head_version" in $$source)) {
            this["head_version"] = "";
        }
        if (!("linked_keg" in $$source)) {
            this["linked_keg"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("installed" in $$source)) {
            this["installed"] = [];
        }
        if (!("dependencies" in $$source)) {
            this["dependencies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormulaInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FormulaInfo {
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("installed" in $$parsedSource) {
            $$parsedSource["installed"] = $$createField10_0($$parsedSource["installed"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField11_0($$parsedSource["dependencies"]);
        }
        return new FormulaInfo($$parsedSource as Partial<FormulaInfo>);
    }
}

export class InstalledListResult {
    "formulae": FormulaInfo[];
    "casks": CaskInfo[];

    /** Creates a new InstalledListResult instance. */
    constructor($$source: Partial<InstalledListResult> = {}) {
        if (!("formulae" in $$source)) {
            this["formulae"] = [];
        }
        if (!("casks" in $$source)) {
            this["casks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InstalledListResult {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formulae" in $$parsedSource) {
            $$parsedSource["formulae"] = $$createField0_0($$parsedSource["formulae"]);
        }
        if ("casks" in $$parsedSource) {
            $$parsedSource["casks"] = $$createField1_0($$parsedSource["casks"]);
        }
        return new InstalledListResult($$parsedSource as Partial<InstalledListResult>);
    }
}

export class KegInfo {
    "version": string;
    "installed_as_dependency": boolean;
    "installed_on_request": boolean;

    /** Creates a new KegInfo instance. */
    constructor($$source: Partial<KegInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("installed_as_dependency" in $$source)) {
            this["installed_as_dependency"] = false;
        }
        if (!("installed_on_request" in $$source)) {
            this["installed_on_request"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KegInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): KegInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KegInfo($$parsedSource as Partial<KegInfo>);
    }
}

export class OutdatedCask {
    "name": string;
    "installed_version": string;
    "current_version": string;

    /** Creates a new OutdatedCask instance. */
    constructor($$source: Partial<OutdatedCask> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("installed_version" in $$source)) {
            this["installed_version"] = "";
        }
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutdatedCask instance from a string or object.
     */
    static createFrom($$source: any = {}): OutdatedCask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutdatedCask($$parsedSource as Partial<OutdatedCask>);
    }
}

export class OutdatedFormula {
    "name": string;
    "installed_versions": string[];
    "current_version": string;
    "pinned": boolean;
    "pinned_version": string;

    /** Creates a new OutdatedFormula instance. */
    constructor($$source: Partial<OutdatedFormula> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("installed_versions" in $$source)) {
            this["installed_versions"] = [];
        }
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("pinned_version" in $$source)) {
            this["pinned_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutdatedFormula instance from a string or object.
     */
    static createFrom($$source: any = {}): OutdatedFormula {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("installed_versions" in $$parsedSource) {
            $$parsedSource["installed_versions"] = $$createField1_0($$parsedSource["installed_versions"]);
        }
        return new OutdatedFormula($$parsedSource as Partial<OutdatedFormula>);
    }
}

export class OutdatedListResult {
    "formulae": OutdatedFormula[];
    "casks": OutdatedCask[];

    /** Creates a new OutdatedListResult instance. */
    constructor($$source: Partial<OutdatedListResult> = {}) {
        if (!("formulae" in $$source)) {
            this["formulae"] = [];
        }
        if (!("casks" in $$source)) {
            this["casks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutdatedListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OutdatedListResult {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formulae" in $$parsedSource) {
            $$parsedSource["formulae"] = $$createField0_0($$parsedSource["formulae"]);
        }
        if ("casks" in $$parsedSource) {
            $$parsedSource["casks"] = $$createField1_0($$parsedSource["casks"]);
        }
        return new OutdatedListResult($$parsedSource as Partial<OutdatedListResult>);
    }
}

export class PackageInfoResult {
    "type": string;
    "name": string;
    "full_name": string;
    "tap": string;
    "desc": string;
    "homepage": string;
    "license": string;
    "current_version": string;
    "installed_version": string;
    "linked_keg": string;
    "pinned": boolean;
    "auto_updates": boolean;
    "token": string;
    "installed": KegInfo[];
    "dependencies": string[];

    /** Creates a new PackageInfoResult instance. */
    constructor($$source: Partial<PackageInfoResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("full_name" in $$source)) {
            this["full_name"] = "";
        }
        if (!("tap" in $$source)) {
            this["tap"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("license" in $$source)) {
            this["license"] = "";
        }
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("installed_version" in $$source)) {
            this["installed_version"] = "";
        }
        if (!("linked_keg" in $$source)) {
            this["linked_keg"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("auto_updates" in $$source)) {
            this["auto_updates"] = false;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = [];
        }
        if (!("dependencies" in $$source)) {
            this["dependencies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageInfoResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageInfoResult {
        const $$createField13_0 = $$createType2;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("installed" in $$parsedSource) {
            $$parsedSource["installed"] = $$createField13_0($$parsedSource["installed"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField14_0($$parsedSource["dependencies"]);
        }
        return new PackageInfoResult($$parsedSource as Partial<PackageInfoResult>);
    }
}

export class SearchItem {
    "name": string;
    "full_name": string;
    "desc": string;
    "tap": string;

    /** Creates a new SearchItem instance. */
    constructor($$source: Partial<SearchItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("full_name" in $$source)) {
            this["full_name"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("tap" in $$source)) {
            this["tap"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchItem($$parsedSource as Partial<SearchItem>);
    }
}

export class SearchResult {
    "formulae": SearchItem[];
    "casks": SearchItem[];

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("formulae" in $$source)) {
            this["formulae"] = [];
        }
        if (!("casks" in $$source)) {
            this["casks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formulae" in $$parsedSource) {
            $$parsedSource["formulae"] = $$createField0_0($$parsedSource["formulae"]);
        }
        if ("casks" in $$parsedSource) {
            $$parsedSource["casks"] = $$createField1_0($$parsedSource["casks"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class TapDetailResult {
    "name": string;
    "remote": string;
    "custom_remote": boolean;
    "formula_names": string[];
    "cask_tokens": string[];
    "last_commit": string;
    "branch": string;

    /** Creates a new TapDetailResult instance. */
    constructor($$source: Partial<TapDetailResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("remote" in $$source)) {
            this["remote"] = "";
        }
        if (!("custom_remote" in $$source)) {
            this["custom_remote"] = false;
        }
        if (!("formula_names" in $$source)) {
            this["formula_names"] = [];
        }
        if (!("cask_tokens" in $$source)) {
            this["cask_tokens"] = [];
        }
        if (!("last_commit" in $$source)) {
            this["last_commit"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TapDetailResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TapDetailResult {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formula_names" in $$parsedSource) {
            $$parsedSource["formula_names"] = $$createField3_0($$parsedSource["formula_names"]);
        }
        if ("cask_tokens" in $$parsedSource) {
            $$parsedSource["cask_tokens"] = $$createField4_0($$parsedSource["cask_tokens"]);
        }
        return new TapDetailResult($$parsedSource as Partial<TapDetailResult>);
    }
}

export class TapResult {
    "name": string;
    "remote": string;
    "custom_remote": boolean;

    /** Creates a new TapResult instance. */
    constructor($$source: Partial<TapResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("remote" in $$source)) {
            this["remote"] = "";
        }
        if (!("custom_remote" in $$source)) {
            this["custom_remote"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TapResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TapResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TapResult($$parsedSource as Partial<TapResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = KegInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FormulaInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CaskInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = OutdatedFormula.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = OutdatedCask.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = SearchItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
