// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(2616047602);
}

export function List(): $CancellablePromise<$models.BrewServicesResult[]> {
    return $Call.ByID(2777797478).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Restart(name: string): $CancellablePromise<void> {
    return $Call.ByID(2331657629, name);
}

export function RestartAll(): $CancellablePromise<void> {
    return $Call.ByID(3045987340);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2620369305, app);
}

export function Start(name: string): $CancellablePromise<void> {
    return $Call.ByID(1162668882, name);
}

export function StartAll(): $CancellablePromise<void> {
    return $Call.ByID(3724611913);
}

export function Stop(name: string): $CancellablePromise<void> {
    return $Call.ByID(3321118994, name);
}

export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(252974089);
}

// Private type creation functions
const $$createType0 = $models.BrewServicesResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
