// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Add(name: string): $CancellablePromise<void> {
    return $Call.ByID(2704427755, name);
}

export function Details(name: string): $CancellablePromise<$models.TapDetailResult | null> {
    return $Call.ByID(894340574, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function List(): $CancellablePromise<$models.TapResult[]> {
    return $Call.ByID(3246455744).then(($result: any) => {
        return $$createType3($result);
    });
}

export function PackageAction(packageType: string, name: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(4044623122, packageType, name, action);
}

export function Remove(name: string): $CancellablePromise<void> {
    return $Call.ByID(833383648, name);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2977152051, app);
}

// Private type creation functions
const $$createType0 = $models.TapDetailResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.TapResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
